services:
  studio:
    image: audio-files-studio
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - C:\bookforge\models:/models
    environment:
      - COQUI_TTS_AGREED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: python src/bookforge/ui/main.py